included:
  - Sources

excluded:
  - .build
  - Tests

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 80

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length: 2
  excluded:
    - id
    - x
    - y
